apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-recreate-backup-pvc
  namespace: <simple-recreate namespace>
  labels:
    foundationservices.cloudpak.ibm.com: simple-recreate-data
spec:
  storageClassName: <storage class>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem